-- ============================================
-- SQL COMPLETO - TABELA DE CONTATOS
-- Execute no Supabase SQL Editor
-- ============================================

-- ============================================
-- PASSO 1: Verificar se a tabela existe
-- ============================================
SELECT EXISTS (
   SELECT FROM information_schema.tables
   WHERE table_schema = 'public'
   AND table_name = 'contatos'
) AS tabela_existe;

-- ============================================
-- PASSO 2: Criar a tabela (se não existir)
-- ============================================
CREATE TABLE IF NOT EXISTS contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    telefone TEXT,
    mensagem TEXT,
    lido BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- PASSO 3: Habilitar RLS
-- ============================================
ALTER TABLE contatos ENABLE ROW LEVEL SECURITY;

-- ============================================
-- PASSO 4: Criar políticas
-- ============================================

-- 4.1: INSERT público (site pode enviar)
CREATE POLICY "public_insert_contatos" ON contatos
    FOR INSERT TO anon WITH CHECK (true);

-- 4.2: SELECT para admin
CREATE POLICY "auth_read_contatos" ON contatos
    FOR SELECT TO authenticated USING (true);

-- 4.3: UPDATE para admin
CREATE POLICY "auth_update_contatos" ON contatos
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

-- 4.4: DELETE para admin
CREATE POLICY "auth_delete_contatos" ON contatos
    FOR DELETE TO authenticated USING (true);

-- ============================================
-- PASSO 5: Conceder permissões (GRANT)
-- ============================================
GRANT INSERT ON public.contatos TO anon;
GRANT SELECT ON public.contatos TO anon;
GRANT SELECT ON public.contatos TO authenticated;
GRANT UPDATE ON public.contatos TO authenticated;
GRANT DELETE ON public.contatos TO authenticated;

-- ============================================
-- PASSO 6: Verificar resultado
-- ============================================
SELECT 'Tabela contatos criada com sucesso!' AS resultado;

-- Ver dados existentes (se houver)
SELECT * FROM contatos LIMIT 10;