-- ============================================
-- COPIE TODO ESTE CÓDIGO E COLE NO SUPABASE SQL EDITOR
-- DEPOIS CLIQUE EM "RUN"
-- ============================================

-- Criar tabela
CREATE TABLE IF NOT EXISTS contatos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    email TEXT NOT NULL,
    telefone TEXT,
    mensagem TEXT,
    lido BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE contatos ENABLE ROW LEVEL SECURITY;

-- Políticas
CREATE POLICY "public_insert_contatos" ON contatos FOR INSERT TO anon WITH CHECK (true);
CREATE POLICY "auth_read_contatos" ON contatos FOR SELECT TO authenticated USING (true);
CREATE POLICY "auth_update_contatos" ON contatos FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "auth_delete_contatos" ON contatos FOR DELETE TO authenticated USING (true);

-- Permissões
GRANT INSERT ON public.contatos TO anon;
GRANT SELECT ON public.contatos TO anon;
GRANT SELECT ON public.contatos TO authenticated;
GRANT UPDATE ON public.contatos TO authenticated;
GRANT DELETE ON public.contatos TO authenticated;

-- Ver resultado
SELECT * FROM contatos LIMIT 5;